#!/bin/sh

ERRORS=0

git rev-parse --quiet --verify HEAD &> /dev/null
if [ $? -eq 1 ]; then
    exit 0
fi

for FILE in `git diff-index HEAD --name-only --cached`; do
    if [ ! -f $FILE ]; then
        continue
    fi

    grep -i 'TODO\|FIXME' $FILE 2>&1 >/dev/null
    if [ $? -eq 0 ]; then
        if [ $ERRORS -eq 0 ]; then
            exec 1>&2
            echo 'error: commit rejected:'
            ERRORS=1
        fi

        echo
        echo $FILE 'contains TODO or FIXME'
        echo
        grep --before-context 1 --after-context 2 --line-number --with-filename -i 'TODO\|FIXME' $FILE
    fi
done

if [ $ERRORS -eq 1 ]; then
    echo
    echo "You may use 'git commit --no-verify' to override this check."
    exit 1
fi

exit
